"""Generate the Stage-1 grid configs into configs/stage1_*.yaml.

Two axes, crossed:

  HORIZON  -- how far back the permanent's memory reaches, in env steps.
              horizon ~= (1/rho) * k * n_steps * num_envs.
              mock_continual: n_steps=256, num_envs=4 -> 1024 env steps per PPO update.
              Phase length is 40 000 steps, so "2 phases" = 80 000 steps is the target
              derived in configs/pt_paper.yaml (average across BOTH tasks, not track one).

  TASK SET -- the reward asymmetry. set_task() takes any float and target = direction *
              target_magnitude (=2.0), so an asymmetric task set needs no code change.
              E_tau[target] is the permanent's optimal content under Theorem 5; when it is
              0 the permanent is structurally empty and PT cannot show retention.

Everything else is mock_continual.yaml verbatim, so the only differences between cells are
the ones named here.
"""
import copy
import pathlib

import yaml

CFG_DIR = pathlib.Path(__file__).resolve().parents[0]
REPO = pathlib.Path(r"e:/update-single task + videos/src_continuous_control")
BASE = REPO / "configs" / "mock_continual.yaml"

STEPS_PER_UPDATE = 256 * 4          # n_steps * num_envs, from mock_continual.yaml
PHASE = 40_000                      # switch interval, from mock_continual.yaml

# (label, rho, k). k=8 is the branch default; the k=30 cell shares a horizon with
# rho005_k8 so that "does k matter beyond the horizon it implies?" is answerable.
PT_CELLS = [
    ("rho50_k8",  0.50,  8),        # branch default -- the control, horizon 0.4 phases
    ("rho15_k8",  0.15,  8),        # horizon ~1.4 phases
    ("rho05_k8",  0.05,  8),        # horizon ~4 phases   <- derived target region
    ("rho15_k30", 0.15, 30),        # horizon ~5 phases, but 3.75x fewer consolidations
]

# (label, tasks, comment). target = direction * 2.0.
TASK_SETS = [
    ("sym",   [1.0, -1.0],        "targets +2 / -2 : E_tau[target]=0, permanent is empty"),
    ("asym",  [1.0, -0.25],       "targets +2 / -0.5 : E_tau[target]=+0.75"),
    ("three", [1.0, 0.25, -0.5],  "targets +2 / +0.5 / -1 : two tasks share a sign"),
]


def horizon(rho, k):
    return (1.0 / rho) * k * STEPS_PER_UPDATE


def main():
    base = yaml.safe_load(BASE.read_text())
    written = []

    for tlabel, tasks, tcomment in TASK_SETS:
        # --- vanilla baseline for this task set ---
        cfg = copy.deepcopy(base)
        cfg["agent"] = "vanilla"
        cfg["tasks"] = tasks
        name = f"stage1_van_{tlabel}"
        header = (
            f"# STAGE 1 -- vanilla baseline, task set '{tlabel}'.\n"
            f"# {tcomment}\n"
            f"# Generated by scratchpad/gen_stage1.py; everything else is mock_continual.yaml.\n"
        )
        (REPO / "configs" / f"{name}.yaml").write_text(header + yaml.safe_dump(cfg, sort_keys=False))
        written.append(name)

        # --- pt_full cells ---
        for plabel, rho, k in PT_CELLS:
            cfg = copy.deepcopy(base)
            cfg["agent"] = "pt_full"
            cfg["tasks"] = tasks
            cfg["rho"] = rho
            cfg["k"] = k
            # Consolidation buffer must hold one full cycle of states, else the permanent
            # regresses on a truncated, biased sample of the cycle it is meant to summarise.
            cfg["consolidation_buffer_size"] = k * STEPS_PER_UPDATE
            h = horizon(rho, k)
            name = f"stage1_pt_{plabel}_{tlabel}"
            header = (
                f"# STAGE 1 -- pt_full, rho={rho} k={k}, task set '{tlabel}'.\n"
                f"# {tcomment}\n"
                f"# Permanent memory horizon ~= (1/rho)*k*1024 = {h:,.0f} env steps "
                f"= {h / PHASE:.1f} phases.\n"
                f"# Generated by scratchpad/gen_stage1.py; everything else is mock_continual.yaml.\n"
            )
            (REPO / "configs" / f"{name}.yaml").write_text(
                header + yaml.safe_dump(cfg, sort_keys=False))
            written.append(name)

    print(f"wrote {len(written)} configs:")
    for n in written:
        print("   ", n)
    print("\nhorizons (env steps / phases of 40k):")
    for plabel, rho, k in PT_CELLS:
        h = horizon(rho, k)
        print(f"    {plabel:10s} rho={rho:<5} k={k:<3} -> {h:9,.0f}  ({h / PHASE:5.1f} phases)")


if __name__ == "__main__":
    main()
