#!/bin/bash
# STAGE 1 -- point-mass grid: does PT-PPO work once the permanent's memory horizon is right,
# and does it need an asymmetric task set?
#
# Two axes, crossed (configs generated by scratchpad/gen_stage1.py):
#
#   HORIZON   rho/k set how far back the permanent's memory reaches:
#               rho50_k8   16k steps  (0.4 phases)  <- the branch default, the control
#               rho15_k8   55k steps  (1.4 phases)
#               rho05_k8  164k steps  (4.1 phases)  <- the derived target region
#               rho15_k30 205k steps  (5.1 phases)  same horizon as rho05_k8, 3.75x fewer
#                                                   consolidations -- isolates k from horizon
#
#   TASK SET  sym   targets +2 / -2      E_tau[target] = 0     permanent structurally empty
#             asym  targets +2 / -0.5    E_tau[target] = +0.75
#             three targets +2/+0.5/-1   two tasks share a sign
#
# WHY THIS ORDER. Running several environments at the branch's default rho/k would produce
# negative results that measure a mis-horizoned permanent, not PT. The horizon is one number
# and it is measurably wrong (FINDINGS/pt_paper.yaml derive ~2 phases; the default gives 0.4).
#
# Runs from the PARENT of src_continuous_control/, per CLAUDE.md. (The absolute-import +
# nested-shim arrangement that briefly forced run-from-inside has been reverted.)
set -u

cd "$(dirname "$0")/../.." || exit 1
if [ ! -d "src_continuous_control" ]; then
  echo "ERROR: run from the PARENT of src_continuous_control/ (cwd=$(pwd))"; exit 1
fi

export CUDA_VISIBLE_DEVICES=""
export OMP_NUM_THREADS=1 MKL_NUM_THREADS=1 OPENBLAS_NUM_THREADS=1 NUMEXPR_NUM_THREADS=1

MAXJOBS=${MAXJOBS:-7}
SEEDS=${SEEDS:-"0 1 2 3 4"}
RUN_TAG=${RUN_TAG:-stage1}
RES_DIR="${RUN_TAG}_results"; LOG_DIR="${RUN_TAG}_logs"

if compgen -G "${RES_DIR}/*/*_scalars.pkl" > /dev/null 2>&1; then
  echo "ERROR: ${RES_DIR}/ already contains results. Use RUN_TAG=<something-new>."
  exit 1
fi
mkdir -p "$LOG_DIR"

TASKSETS="sym asym three"
PT_CELLS="rho50_k8 rho15_k8 rho05_k8 rho15_k30"

echo "=== Stage 1 START $(date)  seeds=[$SEEDS] maxjobs=$MAXJOBS ==="
N=0
for seed in $SEEDS; do
  for TS in $TASKSETS; do
    # vanilla baseline for this task set
    for SPEC in "van_${TS}:vanilla" $(for C in $PT_CELLS; do echo "pt_${C}_${TS}:pt_full"; done); do
      NAME="${SPEC%%:*}"; AGENT="${SPEC#*:}"
      while [ "$(jobs -rp | wc -l)" -ge "$MAXJOBS" ]; do sleep 3; done
      N=$((N+1))
      python -u -m src_continuous_control.train \
          --agent "$AGENT" --config "stage1_${NAME}" --seed "$seed" \
          --no-wandb --no-tb --no-eval \
          --results-dir "${RES_DIR}/${NAME}" --runs-dir "${RES_DIR}/_runs/${NAME}" \
          > "${LOG_DIR}/${NAME}_seed${seed}.log" 2>&1 &
    done
  done
done
wait
echo "=== Stage 1 DONE $(date)  launched ${N} runs ==="
echo
echo "CHECK FIRST -- an inert or saturated permanent makes a cell meaningless:"
echo "  grep -h 'absorbed' ${LOG_DIR}/pt_*.log | tail"
echo "  absorbed_frac is normalised by rho*transient here, so ~1.0 is HEALTHY"
echo "  (it means the permanent absorbed the rho it was asked to), not saturated."
